# Generated by Django 2.1.5 on 2019-02-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
