# Generated by Django 2.1.5 on 2019-02-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190216_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
