# Generated by Django 2.1.5 on 2019-02-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
