# Generated by Django 2.1.5 on 2019-02-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
